const fileOne = {
    "profile": "Profiel",
    "stepper_back": "Terug",
    "stepper_next": "Volgende",
    "stepper_finish": "Klaan",
    "consent_title": "Toestemming",
    "consent_description_agree": "Uw toestemming hebben we nodig voordat u van Wavy Health kunt genieten",
    "consent_description_disagree": "Beantwoord de vragen om te genieten van alle voordelen van Wavy Health",
    "consent_continue": "Doorgaan",
    "consent_start": "Start",
    "consent_information_1": "Wavy is de slimme partner voor je hart. Onze missie is om u als hartpatiënt te helpen je stress te verminderen door inzicht te geven in uw klachten en door proactieve ontspanningsoefeningen aan te bieden.",
    "consent_information_2": "Wavy verzamelt uw profielgegevens, uw levensstijlgegevens en Garmin horloge-gegevens. Alle gegevens worden opgeslagen op de Europese medische OVHcloud. Wavy zal uw gegevens nooit aan derden verkopen en worden alleen intern verwerkt en geanalyseerd. Als inwoner van de Europese Unie heeft u het recht om uw Wavy-account op elk moment te verwijderen.",
    "consent_date": "Ingang: 14-6-'21",
    "consent_button_agree": "Eens",
    "consent_button_disagree": "Oneens",
    "completed_title": "Profiel voltooid!",
    "completed_description": "Bedankt voor het invullen van de vragen, dit helpt Wavy om een persoonlijk profiel op te stellen en om beter met stress om te gaan.",
    "completed_start_using_app": "Gebruik de app",
    "questionnaire_overview_tell_us_more": "Bijna klaar! Nog een paar extra vragen.",
    "questionnaire_overview_notification": "De volgende vragen helpen Wavy om niet te veel notificaties te sturen.",
    "questionnaire_overview_section": "Klik op een sectie om door te gaan:",
    "questionnaire_overview_error_description": "Er ging iets fout! Probeer het opnieuw.",
    "questionnaire_overview_error_button_text": "Opnieuw laden",
    "questionnaire_app_bar_action_skip": "Overslaan",
    "questionnaire_app_bar_action_skip_edit_mode_question": "Overzicht",
    "questionnaire_app_bar_action_skip_edit_mode_overview": "Terug",
    "questionnaire_app_bar_dialog_title": "Weet u het zeker?",
    "questionnaire_app_bar_dialog_description": "U kunt niet alle functies van Wavy gebruiken als u dit overslaat.",
    "questionnaire_app_bar_dialog_button_cancel": "Annuleren",
    "questionnaire_app_bar_dialog_button_skip": "Overslaan",
    "questionnaire_button_clear": "Wissen",
    "questionnaire_button_submit": "Volgende",
    "question_type_year_title": "Selecteer jaar",
    "question_type_year_hint": "Type hier",
    "question_type_time_hint": "Type hier",
    "question_type_binary_no": "Nee",
    "question_type_binary_yes": "Ja",
    "question_type_number_hint": "Type hier",
    "general_title": "Algemeen",
    "question_1": "Wat is uw biologische geslacht?",
    "question_1_option_1": "Vrouw",
    "question_1_option_2": "Man",
    "question_1_option_3": "Overig",
    "question_1_option_4": "Geen antwoord",
    "question_2": "In welk jaar bent u geboren",
    "question_3": "Hoelang bent u (cm)?",
    "question_4": "Hoeveel weegt u (kg)?",
    "question_5": "Heeft u kinderen?",
    "question_6": "Rookt u?",
    "question_7": "Drinkt u alcohol?",
    "question_8": "Drinkt u koffie?",
    "question_9": "Neemt u medicatie?",
    "question_10": "Hoelaat neemt u uw medicatie?",
    "sleep_title": "Slaap",
    "question_11": "Doordeweeks: Hoelaat wordt u wakker?",
    "question_11_extra_information": "De volgende vragen helpen ons uw slaapritme te begrijpen, zo kunnen we afleiding tijdens uw slaap te verminderen.",
    "question_12": "Doordeweeks: Hoelaat gaat u naar bed?",
    "question_13": "Weekend: Hoelaat wordt u wakker?",
    "question_13_option_1": "Vroeg",
    "question_13_option_2": "Laat",
    "question_13_option_3": "Varieert",
    "question_14": "Weekend: Hoelaat gaat u naar bed?",
    "question_14_option_1": "Vroeg",
    "question_14_option_2": "Laat",
    "question_14_option_3": "Varieert",
    "work_title": "Werk",
    "question_15": "Heeft u op dit moment werk?",
    "question_15_extra_information": "De volgende vragen helpen Wavy uw werksituatie begrijpen, zo kunnen we meer gerichte notificaties sturen terwijl u werkt.",
    "question_16": "Wat voor werk heeft u?",
    "question_16_option_1": "Fysiek",
    "question_16_option_2": "Zittend",
    "question_16_option_3": "Staand",
    "question_17": "Hoeveel inspanning levert u op uw werk?",
    "question_17_option_1": "Licht",
    "question_17_option_2": "Neutraal",
    "question_17_option_3": "Zwaar",
    "question_18": "Op welke dagen werkt u meestal?",
    "question_18_option_1": "MA",
    "question_18_option_2": "DI",
    "question_18_option_3": "WO",
    "question_18_option_4": "DO",
    "question_18_option_5": "VR",
    "question_18_option_6": "ZA",
    "question_18_option_7": "ZO",
    "question_19": "Hoeveel uur werkt u dagelijks?",
    "question_20": "Reist u naar het werk?",
    "question_21": "Hoe reist u naar het werk?",
    "question_21_option_1": "Te voet",
    "question_21_option_2": "Met de fiets",
    "question_21_option_3": "Met een E-bike",
    "question_21_option_4": "Openbaar vervoer",
    "question_21_option_5": "Auto",
    "question_22": "Hoeveel minuten duurt de reis naar uw werk?",
    "exercise_title": "Sport",
    "question_23": "Sport u regelmatig?",
    "question_23_extra_information": "De volgende vragen helpen ons uw sportgewoonten te begrijpen, zo kunnen we afleiding tijdens het sporten te verminderen.",
    "question_24": "Op welke dagen sport u meestal?",
    "question_24_option_1": "MA",
    "question_24_option_2": "DI",
    "question_24_option_3": "WO",
    "question_24_option_4": "DO",
    "question_24_option_5": "VR",
    "question_24_option_6": "ZA",
    "question_24_option_7": "ZO",
    "question_25": "Hoeveel minuten sport u gemiddeld?",
    "question_26": "Op welk dagdeel sport u?",
    "question_26_option_1": "Ochtend",
    "question_26_option_2": "Middag",
    "question_26_option_3": "Avond",
    "question_27": "Moet u reizen om te sporten?",
    "core_wearable_connection_chip_connected": "horloge succesvol gekoppeld",
    "core_wearable_connection_chip_disconnected": "geen horloge gekoppeld",
    "main_fab_log_chest_pain": "Log pijn op de borst",
    "main_fab_log_chest_pain_dialog_title": "Ervaart u pijn op de borst?",
    "main_fab_log_chest_pain_dialog_result_description_1": "Uw borstpijn incident is succesvol geregistreerd",
    "main_fab_log_chest_pain_dialog_result_description_2": "In het dagboek kunt u een overzicht van de geregistreerde incidenten terugzien",
    "main_fab_log_chest_pain_dialog_confirmation": "Bevestigen",
    "main_fab_log_chest_pain_dialog_button_negative": "Annuleren",
    "main_fab_log_chest_pain_dialog_button_positive": "Jazeker",
    "main_fab_add_entry": "Voeg een memo in je dagboek toe",
    "main_fab_add_entry_dialog_title": "Waar wil je een memo toevoegen?",
    "main_fab_add_entry_dialog_journal": "Dagboek",
    "main_fab_add_entry_dialog_planner": "Planner",
    "main_fab_add_entry_dialog_description": "Klik waar je de memo toe wil voegen",
    "main_home": "Welkom!",
    "main_home_data_point_stress_level": "Stress niveau",
    "main_home_data_point_cta": "Voer een ontspanningsoefening uit",
    "main_home_data_point_graph_title": "Stress overzicht",
    "main_home_data_point_graph_label": "Stress",
    "main_home_data_point_no_data": "Geen data",
    "main_home_data_point_connect_wearable": "Verbind horloge",
    "main_home_data_point_explanation": "Dit is het meest recent geregistreerde stressniveau. Deze wordt ongeveer elk kwartier geregistreerd. Dit betekent dat de vertraging kan oplopen tot max. 15 minuten",
    "main_home_wearable_selection_bottom_sheet_pairing": "Koppelen",
    "main_home_wearable_selection_bottom_sheet_connect": "Verbinden",
    "main_home_wearable_selection_bottom_sheet_cancel": "Annuleren",
    "main_home_wearable_selection_bottom_sheet_bluetooth_off": "Uw Bluetooth is uit. Schakel deze in om naar uw horloge te zoeken",
    "main_home_wearable_selection_bottom_sheet_searching": "Zoeken",
    "main_home_wearable_selection_bottom_sheet_location_permissions": "Locatierechten zijn nodig om uw horloge te vinden, geef toestemming in de app-instellingen.",
    "main_home_wearable_selection_bottom_sheet_location_permissions_denied": "Instellingen openen",
    "main_home_wearable_selection_bottom_sheet_location_permissions_retry": "Probeer opnieuw",
    "main_home_wearable_selection_bottom_sheet_scan_connect_permissions": "Bluetooth-rechten zijn nodig om uw horloge te vinden, geef toestemming in de app-instellingen.",
    "main_home_wearable_selection_bottom_sheet_scan_connect_permissions_denied": "Instellingen openen",
    "main_home_wearable_selection_bottom_sheet_scan_connect_permissions_retry": "Probeer opnieuw",
    "main_home_wearable_selection_bottom_sheet_battery_restrictions": "Wavy moet batterijbeperkingen hebben om te kunnen worden uitgeschakeld.",
    "main_home_wearable_selection_bottom_sheet_request_permissions": "Toestemming vragen",
    "main_home_graph_no_data": "Geen stressoverzicht data gevonden",
    "main_home_graph_average_data": "Gemiddelde {dataPointName} over de afgelopen {periodOfTime}",
    "main_home_graph_type_week": "Week",
    "main_home_graph_type_week_label": "Dagen",
    "main_home_graph_type_month": "Maand",
    "main_home_graph_type_month_label": "Weken",
    "main_home_graph_type_quarterly": "Kwartaal",
    "main_home_graph_type_quarterly_label": "Maanden",
    "main_home_graph_label_low": "LAAG",
    "main_home_graph_label_normal": "NORMAAL",
    "main_home_graph_label_high": "HOOG",
    "main_journal": "Dagboek",
    "main_journal_overview": "Kalender",
    "main_journal_entries": "Overzicht",
    "main_journal_entries_error_description": "Er ging iets fout! Probeer opnieuw.",
    "main_journal_entries_error_button_text": "Opnieuw laden",
    "main_journal_entries_entry_today": "Vandaag",
    "main_journal_entries_entry_no_data": "Nog geen data",
    "main_journal_entries_entry_dialog_feeling": "Ik voel me",
    "main_journal_entries_entry_dialog_no_feeling": "Geen gevoel beschreven",
    "main_journal_entries_entry_dialog_no_summary": "Geen samenvatting gegeven",
    "main_journal_entries_entry_dialog_close": "Sluiten",
    "main_journal_entries_entry_dialog_button_prev": "Vorige",
    "main_journal_entries_entry_dialog_button_next": "Volgende",
    "main_journal_entries_empty": "Je hebt nog geen memo in je dagboek aangemaakt, laat Wavy weten hoe je je voelt.",
    "main_journal_entries_empty_create": "Maak een memo aan",
    "main_journal_calendar_error_description": "Er ging iets fout! Probeer opnieuw.",
    "main_journal_calendar_error_button_text": "Opnieuw laden",
    "main_journal_planner": "Planner",
    "main_journal_planner_work": "Werk",
    "main_journal_planner_rest": "Ontspanning",
    "main_journal_planner_social": "Sociaal",
    "main_journal_planner_movement": "Beweging",
    "main_journal_planner_error_description": "Er ging iets fout! Probeer opnieuw.",
    "main_journal_planner_error_button_text": "Opnieuw laden",
    "main_relaxation": "Ontspanning",
    "main_relaxation_music": "Muziek",
    "main_relaxation_music_playlist": "Mijn afspeellijst",
    "main_relaxation_music_playlist_create": "Maak afspeellijst",
    "main_relaxation_music_playlist_edit": "Bewerk afspeellijst",
    "main_relaxation_breathing": "Ademen",
    "main_relaxation_breathing_guided": "Begeleide ademhaling",
    "main_relaxation_breathing_description": "Probeer een box-ademhalingsoefening",
    "main_relaxation_breathing_go_to_exercise": "Ga naar oefening",
    "main_settings": "Instellingen",
    "main_settings_app_settings": "App instellingen",
    "main_settings_app_settings_app_language": "App taal",
    "main_settings_app_settings_app_language_dutch": "Nederlands",
    "main_settings_app_settings_app_language_english": "Engels",
    "main_settings_app_settings_app_language_french": "Frans",
    "main_settings_app_settings_app_language_german": "Duits",
    "main_settings_app_settings_wearable_connectivity": "Verbinding horloge",
    "main_settings_app_settings_wearable_connectivity_device_paired": "Apparaat gekoppeld",
    "main_settings_app_settings_wearable_connectivity_dialog_title": "Apparaat verwijderen?",
    "main_settings_app_settings_wearable_connectivity_dialog_description": "Verwijder dit apparaat om verbinding te maken met een nieuw apparaat.",
    "main_settings_app_settings_wearable_connectivity_dialog_button_positive": "Ja",
    "main_settings_app_settings_wearable_connectivity_dialog_button_negative": "Nee",
    "main_settings_profile_settings": "Profiel instellingen",
    "main_settings_profile_settings_profile_information": "Profiel informatie",
    "main_settings_profile_settings_profile_information_edit_profile": "Bewerk profiel",
    "main_settings_profile_settings_profile_information_logout": "Uitloggen",
    "breathing_exercise": "Ademen",
    "breathing_exercise_snack_bar": "Oefening voltooid. Je kunt deze zo vaak herhalen als u wil, voel u vrij om een nieuwe ronde te beginnen als u dat fijn vindt",
    "breathing_exercise_start": "Start",
    "breathing_exercise_stop": "Stop",
    "breathing_phase_one": "Inademen",
    "breathing_exercise_phase_one_description": "Adem langzaam in voor 4 seconden",
    "breathing_phase_two": "Inhouden",
    "breathing_exercise_phase_two_description": "Houd de adem 4 seconden in",
    "breathing_phase_three": "Uitademen",
    "breathing_exercise_phase_three_description": "Adem langzaam uit voor 4 seconden",
    "breathing_phase_four": "Vasthouden",
    "breathing_exercise_phase_four_description": "Houd 4 seconden vast",
    "chest_pain_entries": "{amount,plural, =0{geen pijn op de borst geregistreerd} =1{1 keer pijn op de borst geregistreerd} other{{amount} keer pijn op de borst geregistreerd}}",
    "compose_journal_entry_snack_bar": "Dagboek bijgewerkt",
    "compose_journal_entry_edit": "Bewerk memo in uw dagboek",
    "compose_journal_entry_create": "Maak een memo aan in uw dagboek",
    "compose_journal_entry_error": "Er is iets fout gegaan. Neem contact op met de beheerders als deze fout zich blijft voordoen.",
    "compose_journal_entry_add_feeling": "Gevoel toevoegen",
    "compose_journal_entry_button_discard": "Annuleren",
    "compose_journal_entry_button_save": "Bijwerken",
    "compose_journal_select_feeling_dialog": "Hoe voelt u zich vandaag?",
    "compose_journal_select_feeling_dialog_rate_feeling": "Beoordeel uw gevoel op een schaal van 1 tot 5.",
    "compose_journal_select_feeling_dialog_button_negative": "Annuleren",
    "compose_journal_select_feeling_dialog_button_positive": "Opslaan",
    "compose_journal_select_feedback_app_dialog": "Hoe deed Wavy het vandaag?",
    "compose_journal_select_feedback_app_dialog_rate_feeling": "Hoe goed waarschuwde Wavy u op de momenten waarop u vandaag stress voelde?",
    "compose_journal_select_feedback_app_dialog_button_negative": "Annuleren",
    "compose_journal_select_feedback_app_dialog_button_positive": "Opslaan",
    "compose_journal_select_feedback_alerts_dialog": "Wat ging er mis?",
    "compose_journal_select_feedback_alerts_dialog_radio_not_enough_alerts_title": "Niet genoeg waarschuwingen",
    "compose_journal_select_feedback_alerts_dialog_radio_not_enough_alerts_description": "Ik voelde meer stress dan Wavy aangaf",
    "compose_journal_select_feedback_alerts_dialog_radio_too_many_alerts_title": "Te veel meldingen",
    "compose_journal_select_feedback_alerts_dialog_radio_too_many_alerts_description": "Ik voelde minder stress dan Wavy aangaf",
    "compose_journal_select_feedback_alerts_dialog_radio_wrong_timing_title": "Verkeerde timing",
    "compose_journal_select_feedback_alerts_dialog_radio_wrong_timing_description": "Wavy waarschuwde me wanneer ik niet gestrest was en niet toen ik dat wel was",
    "compose_journal_select_feedback_alerts_dialog_dialog_button_negative": "Annuleren",
    "compose_journal_select_feedback_alerts_dialog_dialog_button_positive": "Opslaan",
    "compose_planner": "Weekplanner",
    "compose_planner_snack_bar": "Weekplanner bijgewerkt",
    "compose_planner_daily_overview": "Dagelijks overzicht",
    "compose_planner_work": "Werk",
    "compose_planner_work_description": "Hoeveel tijd besteed je aan werk?",
    "compose_planner_rest": "Rust",
    "compose_planner_rest_description": "Hoeveel tijd heb je nodig om uit te rusten?",
    "compose_planner_social": "Sociaal",
    "compose_planner_social_description": "Hoeveel tijd heb je nodig voor sociaal contact?",
    "compose_planner_movement": "Beweging",
    "compose_planner_movement_description": "Hoeveel tijd heb je nodig om te bewegen?",
    "compose_playlist": "Afspeellijst bewerken",
    "compose_playlist_search": "Liedjes zoeken",
    "compose_playlist_search_description": "Typ de naam van een lied, artiest of genre",
    "compose_playlist_name": "Mijn afspeellijst",
    "tabs_home": "Home",
    "tabs_journal": "Dagboek",
    "tabs_relaxation": "Ontspanning",
    "tabs_settings": "Instellingen",
    "utils_feeling_type_helper_great": "Geweldig",
    "utils_feeling_type_helper_good": "Goed",
    "utils_feeling_type_helper_so_so": "Middelmatig",
    "utils_feeling_type_helper_bad": "Slecht",
    "utils_feeling_type_helper_awful": "Vreselijk",
    "onboarding_step_one_title": "Begrijp uw stress",
    "onboarding_step_one_description": "Wavy helpt je te begrijpen hoe positieve en negatieve stressmomenten je beïnvloeden.",
    "onboarding_step_one_button_text": "Doorgaan",
    "onboarding_step_two_title": "Krijg grip op uw stress",
    "onboarding_step_two_description": "Wavy helpt u ontspannen door middel van ademhalingsoefeningen.",
    "onboarding_step_two_button_text": "Doorgaan",
    "onboarding_step_three_title": "Houd een dagboek bij voor uw hart",
    "onboarding_step_three_description": "Met Wavy kunt u alledaagse gebeurtenissen markeren in uw digitale dagboek. Dit helpt u bij te houden hoe het met u gaat en hartgerelateerde incidenten met uw arts te delen.",
    "onboarding_step_three_button_text": "Start",
    "unauthenticated_title": "Niet geverifieerd",
    "unauthenticated_description": "Verifieer uw inloggegevens a.u.b. om de app te gebruiken",
    "unauthenticated_button_text": "Log in",
    "angina_tracker":"Angina Tracker",
    "select_date": "Selecteer de datum",
    "click_to_select_a_date": "Klik om datum te selecteren",
    "situation_before": "Situatie",
    "situation_before_at_rest": "Tijdens het ontspannen",
    "situation_before_at_rest_during_the_day": "Overdag",
    "situation_before_at_rest_woken_from_sleep": "Werd wakker",
    "situation_before_at_rest_on_couch_in_the_evening": "s Avonds op de bank",
    "situation_before_at_rest_going_to_sleep": "Onderweg naar bed",
    "situation_before_post_exertion": "Na inspanning",
    "situation_before_post_exertion_walking": "Wandelen",
    "situation_before_post_exertion_showering": "Douchen",
    "situation_before_post_exertion_drying_hair": "Haren drogen",
    "situation_before_post_exertion_house_work": "Huishoudelijk werk",
    "situation_before_post_exertion_others": "Anders",
    "situation_before_environment_pollutants": "Omgevingsfactoren",
    "situation_before_environment_pollutants_noise": "Geluidsoverlast",
    "situation_before_environment_pollutants_lighting": "Verlichting",
    "situation_before_environment_pollutants_crowded_environment": "Drukke omgeving",
    "situation_before_environment_pollutants_others": "Anders",
    "situation_before_stress":"Stress",
    "situation_before_stress_situational_stress": "Stressvolle situatie",
    "situation_before_stress_emotional_stress": "Emotionele stress",
    "situation_before_change_in_weather_conditions": "Verandering in weersomstandigheden",
    "situation_before_change_in_weather_conditions_hot_to_cold": "Warm naar koud",
    "situation_before_change_in_weather_conditions_cold_to_hot": "Koud naar warm",
    "situation_before_change_in_weather_conditions_stormy": "Storm",
    "situation_before_change_in_weather_conditions_others": "Anders (graag specificeren)",
    "situation_before_other_factors": "Andere factoren",
    "situation_before_other_factors_others": "Anders",
    "situation_before_other_factors_unknown": "Onbekend",
    "description_of_symptoms": "Symptomen",
    "description_of_symptoms_chest_pain": "Pijn op de borst",
    "description_of_symptoms_chest_pain_left_side_of_the_chest": "Links",
    "description_of_symptoms_chest_pain_right_side_of_the_chest": "Rechts",
    "description_of_symptoms_chest_pain_central_central_to_the_chest": "In het midden",
    "description_of_symptoms_chest_pain_sharp_stabbing_pain": "Scherpe stekende pijn",
    "description_of_symptoms_chest_pain_pressure": "Druk",
    "description_of_symptoms_chest_pain_ache_cramping": "Pijn / Kramp",
    "description_of_symptoms_chest_pain_burning": "Brandend",
    "description_of_symptoms_chest_pain_others": "Anders ",
    "description_of_symptoms_across_shoulder_blades_back_pain": "Rugpijn bij schouderbladen",
    "description_of_symptoms_across_shoulder_blades_back_pain_cramping": "Kramp",
    "description_of_symptoms_across_shoulder_blades_back_pain_sharp_stabbing_pain": "Scherpe stekende pijn",
    "description_of_symptoms_across_shoulder_blades_back_pain_others": "Anders",
    "description_of_symptoms_jaw_pain": "Kaakpijn",
    "description_of_symptoms_jaw_pain_left_side": "Links",
    "description_of_symptoms_jaw_pain_right_side": "Rechts",
    "description_of_symptoms_jaw_pain_ache": "Pijn",
    "description_of_symptoms_jaw_pain_pins_and_needles": "Tintelingen",
    "description_of_symptoms_jaw_pain_sharp_stabbing_pain": "Scherpe stekende pijn",
    "description_of_symptoms_jaw_pain_others": "Anders",
    "description_of_symptoms_arm_pain": "Pijn in arm",
    "description_of_symptoms_arm_pain_left_side": "Links",
    "description_of_symptoms_arm_pain_right_side": "Rechts",
    "description_of_symptoms_arm_pain_deep_ache_top_of_arm": "Diepe pijn bovenin arm",
    "description_of_symptoms_arm_pain_deep_ache_elbow": "Diepe pijn in elleboog",
    "description_of_symptoms_arm_pain_others": "Anders",
    "description_of_symptoms_exhaustion": "Uitputting",
    "description_of_symptoms_exhaustion_cannot_keep_eyes_open": "Kan ogen niet openhouden/wil slapen",
    "description_of_symptoms_exhaustion_cannot_perform_usual_functions": "Kan gewone taken niet uitvoeren",
    "description_of_symptoms_exhaustion_others": "Anders",
    "description_of_symptoms_other_factors": "Andere symptomen",
    "description_of_symptoms_other_factors_shortness_of_breath": "Kortademig",
    "description_of_symptoms_other_factors_fizziness_under_skin": "Bruisend gevoel onder de huid",
    "description_of_symptoms_other_factors_others": "Anders",
    "duration_of_symptoms": "Duur van symptomen",
    "duration_of_symptoms_duration": "Duur",
    "duration_of_symptoms_duration_less_than_one_minute": "Minder dan 1 minuut",
    "duration_of_symptoms_duration_lasting_one_to_ten_minutes": "1-10 minuten",
    "duration_of_symptoms_duration_between_ten_to_thirty_minutes": "10-30 minuten",
    "duration_of_symptoms_duration_more_than_thirty_minutes": "Meer dan 30 minuten",
    "duration_of_symptoms_duration_unknown": "Weet ik niet",
    "how_to_calm": "Gecalmeerd door",
    "how_to_calm_taking_gtn_spray_tablet": "GTN spray/tablet",
    "how_to_calm_gtn_spray_tablet_one_dose_two_sprays": "Eén dosis / Twee sprays",
    "how_to_calm_gtn_spray_tablet_two_dosees": "Twee doses",
    "how_to_calm_gtn_spray_tablet_three_doses": "Drie doses",
    "how_to_calm_gtn_spray_tablet_others": "Anders",
    "how_to_calm_other_actions": "Andere aanpak",
    "how_to_calm_other_actions_deep_breathing": "Ademhalingsoefening",
    "how_to_calm_other_actions_rest": "Rusten",
    "how_to_calm_other_actions_meditation": "Meditatie",
    "how_to_calm_other_actions_called_one_one_two": "112 gebeld",
    "how_to_calm_other_actions_gp_contacted": "Contact gehad met huisarts",
    "how_to_calm_other_actions_a_and_e_visited": "SEH bezocht",
    "how_to_calm_other_actions_ambulance_called": "Ambulance gebeld",
    "how_to_calm_other_actions_others": "Anders (graag specificeren)",
    "observations": "Ander tijdstip en overige observaties",
    "observations_blood_pressure": "Tijd / Bloeddruk / O2 / etc.",
    "observations_blood_pressure_please_specify_any_observations": "Graag datum en tijd invullen indien klachten eerder waren",
    "angina_tracker_success": "Je klachtenlogboek is succesvol opgeslagen!",
    "angina_tracker_error": "Sorry, er is iets fout gegaan!",
    "angina_tracker_save": "Opslaan",
    "main_settings_app_settings_faq": "Veelgestelde vragen",
    "main_settings_app_settings_go_to_faq_page": "Naar de webpagina met veelgestelde vragen",
    "main_home_stress_level_low":"LAAG",
    "main_home_stress_level_normal":"NORMAAL",
    "main_home_stress_level_high":"HOOG",
    "main_home_wearable_paired_successfully_connection_status":"Verbindingsstatus",
    "main_home_wearable_paired_successfully_dialog":"Als de stip rood is, is er voor langere tijd geen data gemeten",
    "main_home_stress_overview_dialog_explanation":"Uitleg",
    "main_home_stress_overview_dialog_red":"Wavy registreerde dit uur minstens 1 hoog stressniveau bij u.",
    "main_home_stress_overview_dialog_blue":"Wavy registreerde dit uur een normaal stressniveau bij u.",
    "main_home_stress_overview_dialog_green":"Wavy registreerde dit uur minstens 1 laag stressniveau bij u.",
    "main_home_stress_overview_dialog_grey":"Wavy heeft tijdens dit uur geen stressniveau vastgelegd.",
    "core_wearable_connection_chip_latest_measurement":"LAATSTE METING",
    "core_wearable_connection_chip_measurement_details":"Details van de meting",
    "core_wearable_connection_chip_measurement_description":"Wavy toont hier of uw meting succesvol is opgenomen",
    "core_wearable_connection_chip_measurement_details_green":"Stressniveau succesvol geregistreerd.",
    "core_wearable_connection_chip_measurement_details_red":"Geen stressniveau geregistreerd, controleer of uw horloge correct is aangesloten.",
    "core_wearable_connection_chip_measurement_no_data": "Al even geen data verzameld",
     "step_one_breathing_exo": "Stap 1. Adem in",
    "step_two_breathing_exo": "Stap 2. Houd je adem in",
    "step_three_breathing_exo": "Stap 3. Adem rustig uit",
    "step_four_breathing_exo": "Stap 4. Pause, houd je adem in",
    "breathing_help_extra_text": "Elke stap duurt 4 seconden. Is dat te lang voor jou? Gebruik dan de oefen versie van 2 seconden per stap! Dit zal je ook helpen met stress reductie.",
    "breathing_dialog_title": " Box ademhalingstechniek?",
    "breathing_exercise_start": "Start",
    "breathing_exercise_stop": "Stop",
    "breathing_practice_phase_one": "Inademen",
    "breathing_practice_phase_one_description": "Adem langzaam in gedurende 2 seconden",
    "breathing_practice_phase_two": "Inhouden",
    "breathing_practice_phase_two_description": "Houd de adem 2 seconden in",
    "breathing_practice_phase_three": "Uitademen",
    "breathing_practice_phase_three_description": "Adem langzaam uit gedurende 2 seconden",
    "breathing_practice_phase_four": "Vasthouden",
    "breathing_practice_phase_four_description": "Houd de adem 2 seconden vast"
    }